# Generated by Django 6.0.6 on 2026-08-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="prefix_name",
            field=models.CharField(
                choices=[("นาย", "นาย"), ("นาง", "นาง"), ("นางสาว", "นางสาว")],
                default="นาย",
                max_length=10,
            ),
        ),
    ]
