# Generated by Django 6.0.6 on 2026-08-10 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.major",
            ),
        ),
    ]
