# Generated by Django 6.0.6 on 2026-08-24 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_student_major"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="หมวดหมู่วิชา"
                    ),
                ),
            ],
            options={
                "verbose_name": "หมวดหมู่วิชา",
                "verbose_name_plural": "หมวดหมู่วิชา",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="รหัสวิชา"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="ชื่อวิชา")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="myapp.category",
                        verbose_name="หมวดหมู่",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายวิชา",
                "verbose_name_plural": "รายวิชา",
                "ordering": ["code"],
            },
        ),
    ]
