# Generated by Django 6.0.6 on 2026-08-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_category_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["sub_code"],
                "verbose_name": "รายวิชา",
                "verbose_name_plural": "รายวิชา",
            },
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="code",
            new_name="sub_code",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="category",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="title",
        ),
        migrations.AddField(
            model_name="subject",
            name="sub_name",
            field=models.CharField(default="", max_length=100, verbose_name="ชื่อวิชา"),
            preserve_default=False,
        ),
    ]
