# Generated by Django 6.0.6 on 2026-08-31 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_subject_options_rename_code_subject_sub_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrolls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.subject"
                    ),
                ),
            ],
            options={
                "verbose_name": "การลงทะเบียน",
                "verbose_name_plural": "การลงทะเบียน",
            },
        ),
    ]
