# Generated by Django 6.0.6 on 2026-08-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_enrolls"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolls",
            name="semester",
            field=models.CharField(
                choices=[
                    ("1/2569", "1/2569"),
                    ("2/2569", "2/2569"),
                    ("3/2569", "3/2569"),
                ],
                default="1/2569",
                max_length=10,
            ),
        ),
    ]
